Update README.md
ton-blockchain/wallet-contract pull request #79
Opened 2024-09-20 04:16 UTC by Kaku9872

2024-09-20 22:36 UTC, JDJD24-af approved these changes

2024-09-25 13:50 UTC, NaNOteh approved these changes

2024-09-27 18:29 UTC, MrG9090 approved these changes

2024-10-09 15:05 UTC, Mnj110 approved these changes

2024-10-09 20:31 UTC, NaNOteh approved these changes

2024-10-09 20:40 UTC, MrG9090 approved these changes

2024-10-09 22:31 UTC, Tommyherself commented
Thanks you

2024-10-22 19:34 UTC, MrG9090 approved these changes

2024-10-22 20:58 UTC, Freshte-h-10 approved these changes

2024-10-22 21:02 UTC, NaNOteh approved these changes

2024-10-22 21:14 UTC, MrG9090 approved these changes

2024-10-28 20:38 UTC, Earlymoney1782 requested changes

2024-10-28 20:38 UTC, Earlymoney1782 commented on README.md
>  destination address.
UQBI6I6L1TP8XiVxBI3pyCZFLvrpC8jhjfvxGCEYUs3KZyas

2024-10-29 11:02 UTC, MrG9090 approved these changes

2024-10-29 22:05 UTC, NaNOteh approved these changes
###

2024-11-16 23:59 UTC, Meroksa approved these changes

2024-11-17 00:31 UTC, Mnj110 commented
I love you baby


در یکشنبه 17 نوامبر 2024 در 3:29 Amir mohamed ***@***.***>
نوشت:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ton-blockchain/wallet-contract/pull/79#pullrequestreview-2440826810>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BLWWRJMNNVM5CCVMIIBZWND2A7L6VAVCNFSM6AAAAABORGVZFKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINBQHAZDMOBRGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-11-17 01:14 UTC, winnydebug commented
🆔   773181909 🆔   773181909 🆔   773181909 🆔   773181909 🆔   773181909

2024-11-17 01:16 UTC, MrG9090 approved these changes

2024-11-17 10:21 UTC, MrG9090 approved these changes

2024-11-17 10:29 UTC, Mnj110 commented
Hi have good day

I love you baby


در یکشنبه 17 نوامبر 2024 در 4:47 MrG9090 ***@***.***> نوشت:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ton-blockchain/wallet-contract/pull/79#pullrequestreview-2440832863>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BLWWRJLTX27VBICAULCPHXD2A7VB5AVCNFSM6AAAAABORGVZFKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINBQHAZTEOBWGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-11-17 10:47 UTC, MrG9090 approved these changes

2024-12-21 16:36 UTC, MrG9090 approved these changes

2024-12-21 18:29 UTC, closed without merging